### ISSUE TITLE
Syntax errors in sparCC.py

### ISSUE THREAD

**Issue by Up4itat24** [luispedro/sparcc#1]
Hello!

I'm relatively new to python so my apologies if this is a lame question. Im hoping to use sparCC for doing correlations on my ITS compositional data. I downloaded the scripts from the repository and am trying to go through the example with the fake data set provided. 

But when I run 
python SparCC.py example/fake_data.txt -i 5 --cor_file=example/basis_corr/cor_sparcc.out

I get the following error:

 File "SparCC.py", line 181
    raise ValueError 'Can not detect correlations between compositions of <4 components (%d given)'   %k     
                                                                                                                                                                         ^
SyntaxError: invalid syntax

I previously got a syntax error when line 181 read   raise ValueError, 'Can not detect correlations between compositions of <4 components (%d given)'   %k     

and it did not like the comma after ValueError. Now after removing that it doesn't like the quotation closing the string. 

I would really appreciate any help on fixing the syntax errors I'm getting! 

Thanks!

**Comment by luispedro** [comment]
Hi, This is not the main sparCC repository. To be frank, I don't remember why I have a copy as it seems to be just an older version of the code. I will delete later

**Comment by luispedro** [comment]
I probably meant to fix something/improve something on the code, but I don't remember what it could be

**Comment by Up4itat24** [comment]
Oh i see! there seems to be quite a few repositories for sparCC, do you know which one is the main one by chance?

**Comment by luispedro** [comment]
No, sorry.
